export const SET_USER="SET_USER";
export const SET_RECIPES="SET_RECIPES";
export const GET_USER="GET_USER";
export const GET_RECIPES="GET_USER";
export const ADD_RECIPES="ADD_RECIPES";
export const DELETE_RECIPE="DELETE_RECIPE";
export const ADD_CATEGORY="ADD_CATEGORY";
export const ADD_PRODUCT="ADD_PRODUCT";
export const ADD_SHOPPING_CART="ADD_SHOPPING_CART";
export const DELTE_PRODUCT="DELTE_PRODUCT";
export const GET_CATEGOIES="GET_CATEGOIES";
export const EDITE_RECIPES="EDITE_RECIPES"


